### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Everlastdg** [sevagas/macro_pack#85]
Running on Win10
pip3 install -r requirements.txt - all good and installed

running
echo "cmd /c notepad.exe" | macro_pack.exe -t CMD -G test.hta --unicode-rtlo=pgn

[+] Preparations...
   [-] Waiting for piped input feed...
   [-] Target output format: HTML Application
   [-] Temporary working dir: REDACTED
 [+] Inject png false extension with unicode RTLO
   [-] Extension .hta
   [-] File name modified to: REDACTED
 [+] Prepare HTML Application file generation...
   [-] Check if VBA->VBScript is possible...
 [+] Generating source code from template...
 [!] Exception caught!
Traceback (most recent call last):
  File "macro_pack.py", line 298, in main
  File "payload_builder.py", line 51, in run
  File "templates\template_factory.py", line 400, in run
  File "templates\template_factory.py", line 370, in _generation
  File "templates\template_factory.py", line 50, in _processCmdTemplate
  File "mp_module.py", line 107, in fillInputParams
IndexError: list index out of range
 [+] Cleaning...
 Done!

**Comment by sevagas** [comment]
Hi are you running the command line from CMD or the Powershell console?
Powershelll console support was not included in community version

**Comment by Everlastdg** [comment]
that explains a lot. true, in was powershell. all good in cmd - thanks!
